### ISSUE TITLE
Always build with PNG library?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2c#112]
We have this option in CMakeLists.txt:

`option(USE_PNG      "Use PNG library"      ON)
`
Is there ever a reason to build without the PNG library? I believe it is available everywhere.

Extra options mean extra code to handle them, and extra testing needed. Currently we are not testing for non-PNG builds. Can we just always require PNG?

**Comment by DusanJovic-NOAA** [comment]
We (NCEP/EMC) by default always enable PNG (and JPEG)  compression. But it should be optional, so that users can turn it OFF if they do not need it.

**Comment by edwardhartnett** [comment]
Do you know of any outside users?

As I mention, more options means more testing, which currently we are not doing. Therefore, it is not free. Unless there is a strong reason to make the PNG library optional, we will make it mandatory. If we know of any internal users who have a need to build without PNG, that would be a strong reason to keep the option. If we know of some external users who need to build without PNG, that would be a less strong reason but still a reason.

If, as I suspect, everyone builds with PNG anyway, then that's a good reason to remove this option, and the extra test burden that goes with it.

**Comment by DusanJovic-NOAA** [comment]
I often build g2c without any external dependency if I know I do not need PNG or JPEG compression. We need to preserve that capability. Testing should detect which build options are enabled/disabled and run or not run corresponding tests.

**Comment by edwardhartnett** [comment]
Very well.

**Comment by edwardhartnett** [comment]
Apparently you don't build without PNG code, because that capability does not seem to be working.

So once again this issue has come up. Is there a use case for building g2c without PNG? Given that you have been building it with PNG all this time, it seems that's OK.

So do we need to preserve (or add) this capability? The usual rule with libraries is to require dependencies if they can be easily found everywhere. PNG is everywhere - why do we even need to build without it?

**Comment by DusanJovic-NOAA** [comment]
I do build (in some projects) g2c without any external library, And it works, or it used to work. If it's broken we need to restore that capability. For example in projects in which I know I will not be creating or reading files using PNG compression I can simply add this repository as a submodule and not require any external dependency other than C compiler. I never heard of that rule that if external library (dependency) is easily found it should be mandatory, where does this rule come from. Is this new EMC rule or just some random rule from somebody else?

**Comment by DusanJovic-NOAA** [comment]
```
$ cmake .. -DUSE_PNG=OFF -DUSE_Jasper=OFF     
-- The C compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Setting build type to 'Release' as none was specified.
-- Will not build PNG support
-- Will not build Jasper support
-- Will not build OpenJPEG support
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dusan/sufs/simple-ufs/libs/NCEPLIBS-g2c-1.6.4/build

$ make 
[  1%] Building C object CMakeFiles/g2c.dir/src/cmplxpack.c.o
[  3%] Building C object CMakeFiles/g2c.dir/src/compack.c.o
[  5%] Building C object CMakeFiles/g2c.dir/src/comunpack.c.o
[  7%] Building C object CMakeFiles/g2c.dir/src/dec_jpeg2000.c.o
[  9%] Building C object CMakeFiles/g2c.dir/src/dec_png.c.o
[ 11%] Building C object CMakeFiles/g2c.dir/src/decenc_openjpeg.c.o
[ 13%] Building C object CMakeFiles/g2c.dir/src/drstemplates.c.o
[ 15%] Building C object CMakeFiles/g2c.dir/src/enc_jpeg2000.c.o
[ 17%] Building C object CMakeFiles/g2c.dir/src/enc_png.c.o
[ 19%] Building C object CMakeFiles/g2c.dir/src/g2_addfield.c.o
[ 21%] Building C object CMakeFiles/g2c.dir/src/g2_addgrid.c.o
[ 23%] Building C object CMakeFiles/g2c.dir/src/g2_addlocal.c.o
[ 25%] Building C object CMakeFiles/g2c.dir/src/g2_create.c.o
[ 26%] Building C object CMakeFiles/g2c.dir/src/g2_free.c.o
[ 28%] Building C object CMakeFiles/g2c.dir/src/g2_getfld.c.o
[ 30%] Building C object CMakeFiles/g2c.dir/src/g2_gribend.c.o
[ 32%] Building C object CMakeFiles/g2c.dir/src/g2_info.c.o
[ 34%] Building C object CMakeFiles/g2c.dir/src/g2_miss.c.o
[ 36%] Building C object CMakeFiles/g2c.dir/src/g2_unpack1.c.o
[ 38%] Building C object CMakeFiles/g2c.dir/src/g2_unpack2.c.o
[ 40%] Building C object CMakeFiles/g2c.dir/src/g2_unpack3.c.o
[ 42%] Building C object CMakeFiles/g2c.dir/src/g2_unpack4.c.o
[ 44%] Building C object CMakeFiles/g2c.dir/src/g2_unpack5.c.o
[ 46%] Building C object CMakeFiles/g2c.dir/src/g2_unpack6.c.o
[ 48%] Building C object CMakeFiles/g2c.dir/src/g2_unpack7.c.o
[ 50%] Building C object CMakeFiles/g2c.dir/src/gbits.c.o
[ 51%] Building C object CMakeFiles/g2c.dir/src/getdim.c.o
[ 53%] Building C object CMakeFiles/g2c.dir/src/getpoly.c.o
[ 55%] Building C object CMakeFiles/g2c.dir/src/gridtemplates.c.o
[ 57%] Building C object CMakeFiles/g2c.dir/src/int_power.c.o
[ 59%] Building C object CMakeFiles/g2c.dir/src/jpcpack.c.o
[ 61%] Building C object CMakeFiles/g2c.dir/src/jpcunpack.c.o
[ 63%] Building C object CMakeFiles/g2c.dir/src/misspack.c.o
[ 65%] Building C object CMakeFiles/g2c.dir/src/mkieee.c.o
[ 67%] Building C object CMakeFiles/g2c.dir/src/pack_gp.c.o
[ 69%] Building C object CMakeFiles/g2c.dir/src/pdstemplates.c.o
[ 71%] Building C object CMakeFiles/g2c.dir/src/pngpack.c.o
[ 73%] Building C object CMakeFiles/g2c.dir/src/pngunpack.c.o
[ 75%] Building C object CMakeFiles/g2c.dir/src/rdieee.c.o
[ 76%] Building C object CMakeFiles/g2c.dir/src/reduce.c.o
[ 78%] Building C object CMakeFiles/g2c.dir/src/seekgb.c.o
[ 80%] Building C object CMakeFiles/g2c.dir/src/simpack.c.o
[ 82%] Building C object CMakeFiles/g2c.dir/src/simunpack.c.o
[ 84%] Building C object CMakeFiles/g2c.dir/src/specpack.c.o
[ 86%] Building C object CMakeFiles/g2c.dir/src/specunpack.c.o
[ 88%] Linking C static library libg2c.a
[ 88%] Built target g2c
[ 90%] Building C object tests/CMakeFiles/tst_g2_create.dir/tst_g2_create.c.o
[ 92%] Linking C executable tst_g2_create
[ 92%] Built target tst_g2_create
[ 94%] Building C object tests/CMakeFiles/tst_decode.dir/tst_decode.c.o
[ 96%] Linking C executable tst_decode
[ 96%] Built target tst_decode
[ 98%] Building C object tests/CMakeFiles/tst_gbits.dir/tst_gbits.c.o
[100%] Linking C executable tst_gbits
[100%] Built target tst_gbits

```
