### ISSUE TITLE
Version 1.6.2 release notes are wrong.

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [NOAA-EMC/NCEPLIBS-g2c#114]
https://github.com/NOAA-EMC/NCEPLIBS-g2c/releases/tag/v1.6.2

_We are pleased to announce the version 1.6.2 release of NCEPLIBS-g2 library._ - Incorrect. Library is g2c, not g2.

_The NCEPLIBS-g2 library contains Fortran 90 decoder/encoder routines for GRIB edition 2, as well as indexing/searching utility routines._  - Also incorrect. The library contains C decoder/encode routines, not Fortran and there are no indexing/searching routines.

**Comment by edwardhartnett** [comment]
Thanks for pointing this out. I have corrected the 1.6.2 release notes, and also the draft notes for the 1.6.3 release.

**Comment by DusanJovic-NOAA** [comment]
There are no "indexing/searching utility routines" in this library.

**Comment by DusanJovic-NOAA** [comment]
Version 1.6.3 has already been released by NCO. Use some other version number to avoid confusion between NCEPLIBS-g2c and g2clib.

**Comment by edwardhartnett** [comment]
How did NCO release a version of this library without us? ;-)

**Comment by DusanJovic-NOAA** [comment]
They maintain NCEPs official release of g2c library, named g2clib.

**Comment by edwardhartnett** [comment]
Are you referring to this: https://github.com/weathersource/g2clib?

I don't see any 1.6.3 tag or release on this library either.

Which library is used by the UFS? Do you know why we have two versions of this code?

**Comment by DusanJovic-NOAA** [comment]
No. I'm referring to official NCO page https://www.nco.ncep.noaa.gov/pmb/codes/GRIB2/
I have no idea what weathersource is, looks like some private company. They just took the code from NCO and created their own repository.
UFS uses g2 library.
