### ISSUE TITLE
Skip the 1.6.3 release - next release should be 1.6.4

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2c#115]
The NCO has done a 1.6.3 release of g2clib. To avoid confusion, we will call the next release 1.6.4.

**Comment by Hang-Lei-NOAA** [comment]
There was a release of v1.6.3 of g2c. I don't know why it is gone. NCO is asking about it, since it addressed some issues inv1.6.2.  NCO has done the work based on v1.6.3. 
We need to solve this issue immediately.

**Comment by kgerheiser** [comment]
There's no history of a version 1.6.3. There's no `v1.6.3` tag, and the `VERSION` file was never updated. Do you know when it was made or what commit it points to? There's not much of a history in this repo aside from the past two weeks.

**Comment by Hang-Lei-NOAA** [comment]
Okay, I will check with NCO and post here or email you. Thanks,

**Comment by edwardhartnett** [comment]
We already checked with NCO and this release was actually done by us. ;-)

> Arun,
> Yes, This changes bought back to the repository and Kyle or Hang built it in hpc-stack (2/9).
> It's been done through branches: https://github.com/NOAA-EMC/NCEPLIBS-g2c/tree/g2c_ver1.6.3
> 
> Thanks,
> 
> Boi

So we will do a 1.6.4 release when the documentation is complete (very soon), and we will move on. In future, all releases will be done via GitHub releases, no longer via branches or tags.

**Comment by edwardhartnett** [comment]
@BoiVuong-NOAA what changes were in the 1.6.3 release? Are there issues for them?

Are you sure that those changes were brought back to the develop branch?

**Comment by BoiVuong-NOAA** [comment]
I requested a PR but i could not merge it back to the develop branch. I have asked Kyle for help.  Would you check with Kyle ?

**Comment by edwardhartnett** [comment]
What code files did you change in your branch?

**Comment by BoiVuong-NOAA** [comment]
I changed the grib2.h and cmakelist.txt

**Comment by kgerheiser** [comment]
There's a couple of commits here: https://github.com/NOAA-EMC/NCEPLIBS-g2c/commits/g2c_ver1.6.3. Looks pretty easy to merge.

**Comment by BoiVuong-NOAA** [comment]
Would you help me to merge it to the develop branch ? Thanks.  I recalled that I could not merge to the develop branch because of permissions.

**Comment by edwardhartnett** [comment]
I will do the merge. I'll take a look tomorrow...

**Comment by kgerheiser** [comment]
The code changes are easy to merge with removing `__64bit__`, but there's also a unit test with Make and Bash (to run on WCOSS) that needs to be made generic.

**Comment by edwardhartnett** [comment]
OK, I dropped this one due to the AGU deadline... I will take a look at this next.

**Comment by edwardhartnett** [comment]
OK, 1.6.4 has been released. I will close this issue.
