### ISSUE TITLE
Should we prohibit using OpenJPEG=On and USE_Jasper=On in cmake build?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2c#120]
We have this in CMakeLists.txt:

```
# Handle user options.
option(ENABLE_DOCS "Enable generation of doxygen-based documentation." OFF)
option(USE_PNG      "Use PNG library"      ON)
option(USE_Jasper   "Use Jasper library"   ON)
option(USE_OpenJPEG "Use OpenJPEG library" OFF)

```

When using Jasper, USE_JPEG2000 is defined. When using OpenJPEG, USE_OPENJPEG is defined.

In the file src/decenc_openjpeg.c we have this:

`#if !defined USE_JPEG2000 && defined USE_OPENJPEG
`

This seems to imply that either USE_JPEG2000 or USE_OPENJPEG should be define, but not both. Is that correct?

Because CMake allows us to turn on both...

**Comment by kgerheiser** [comment]
Yes, they both declare routines with the same name. It should be one or the other.

**Comment by edwardhartnett** [comment]
And yet the build does work with both on! OK, I will change the CMakeLists.txt file to only allow one or the other of these.

**Comment by BoiVuong-NOAA** [comment]
Please assign this task to nceplibs team.  I am in the VPPPGB branch and having some priority tasks for NCEP operational.

**Comment by edwardhartnett** [comment]
@BoiVuong-NOAA and @DusanJovic-NOAA I only assigned you guys to help answer the question. The work will be done by the NCEPLIBS team.

**Comment by BoiVuong-NOAA** [comment]
I see.  I think Dusan added that routine for USE_JPEG2000 or USE_OPENJPEG.

**Comment by Hang-Lei-NOAA** [comment]
USE_JPEG2000 should be the default
