### ISSUE TITLE
Make OpenJPEG the default, instead of Jasper?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2c#138]
@Hang-Lei-NOAA suggests, in #120, that OpenJPEG be the default choice as the JPEG library.

Hang, why do you think this?

Anyone else have any thoughts on this? Are we trying to move away from Jasper?

**Comment by Hang-Lei-NOAA** [comment]
I don't think that it is necessary any more.
The background is that Jasper was told of "no further development/support".
But now, the jasper is continuously developing forward.
We now have jasper/2.0.25 solves everything.

**Comment by BrianCurtis-NOAA** [comment]
They're both open source, and both seem to have active development as of late. There seems to be only one person committing to jasper, while there's a couple/few people committing to OpenJPEG. I don't see why we can't stay the course for now. If the Jasper developer gets burnt out again, we may need to bring this up again then.

**Comment by edwardhartnett** [comment]
OK, we will continue with Jasper as the default.
