### ISSUE TITLE
In drstemplates.c we have extdrstemplate() which handles template 1, but there is no template 1

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2c#152]
We have this code:

```
gtemplate *
extdrstemplate(g2int number, g2int *list)
{
    gtemplate *new;
    g2int index, i;

    index = getdrsindex(number);
    if (index == -1)
        return(0);

    new = getdrstemplate(number);

    if (!new->needext)
        return(new);

    if (number == 1)
    {
        new->extlen = list[10] + list[12];
        new->ext = malloc(sizeof(g2int) * new->extlen);
        for (i = 0; i < new->extlen; i++)
        {
            new->ext[i] = 4;
        }
    }
    return(new);

```

However, in drstemplates.h, there is no template number 1:

```
const struct drstemplate templatesdrs[MAXDRSTEMP] =
{
    /** 5.0: Grid point data - Simple Packing */
    { 0, 5, 0, {4,-2,-2,1,1} },
    /** 5.2: Grid point data - Complex Packing */
    { 2, 16, 0, {4,-2,-2,1,1,1,1,4,4,4,1,1,4,1,4,1} },
    /** 5.3: Grid point data - Complex Packing and spatial differencing */
    { 3, 18, 0, {4,-2,-2,1,1,1,1,4,4,4,1,1,4,1,4,1,1,1} },
    /** 5.50: Spectral Data - Simple Packing */
    { 50, 5, 0, {4,-2,-2,1,4} },
    /** 5.51: Spherical Harmonics data - Complex packing */
    { 51, 10, 0, {4,-2,-2,1,-4,2,2,2,4,1} },
/*           5.1: Matrix values at gridpoint - Simple packing */
/*         { 1, 15, 1, {4,-2,-2,1,1,1,4,2,2,1,1,1,1,1,1} }, */
    /** 5.40: Grid point data - JPEG2000 encoding */
    { 40, 7, 0, {4,-2,-2,1,1,1,1} },
    /** 5.41: Grid point data - PNG encoding */
    { 41, 5, 0, {4,-2,-2,1,1} },
    /** 5.40000: Grid point data - JPEG2000 encoding */
    { 40000, 7, 0, {4,-2,-2,1,1,1,1} },
    /** 5.40010: Grid point data - PNG encoding */
    { 40010, 5, 0, {4,-2,-2,1,1} }
} ;
```

@BoiVuong-NOAA do you know why we have code to deal with DRS template 1, but we have no template 1?

**Comment by BoiVuong-NOAA** [comment]
No, I do not know either. These code written by developer and I did not get any explanations.

**Comment by edwardhartnett** [comment]
I have sent an email to the original code author...

**Comment by edwardhartnett** [comment]
From Stephen Gilbert:


> DRS Template 5.1 - Matrix Value at Grid Point is included in the GRIB2 specification.  It's definition
> also appears in drstemplates.h, but it is currently commented out.
> 
> This encoder/decoder was written in the early days of GRIB2 adoption as a standard.  It was used to
> help WMO validate the templates in the specification by sharing GRIB2 encoded message with other
> organizations to verify that the data could be transmitted and processed successfully.
> 
> We did not have a use case for DRS template 5.1 at that time and did not produce any GRIB2 messages
> using that template.  It appears that other organizations did not work on it as well.  The latest GRIB2
> specification still includes the DRS Template 5.1 definition, but there is a disclaimer to use it with caution,
> since it has not yet been validated.
> I assume we commented it out because it was not validated, which means it's definition could possibly change
> during any validation attempts in the future.
>

**Comment by edwardhartnett** [comment]
See #155.

**Comment by edwardhartnett** [comment]
OK, I think we should remove the exdrstemplate() function, since there are no cases when it is used (i.e. no DRS templates with extensions, except 5.1, which we are not supporting.

If one day we support 5.1 we can recover or recreate this code easily. Until then, let clean it out to keep our library as small and simple as possible.

I will do this after the currently open PRs are merged.

**Comment by edwardhartnett** [comment]
OK, instead, I have commented out the code for this template, just as the template itself is commented out.
