### ISSUE TITLE
extra entries in drstemplates don't appear in WMO docs...

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2c#155]
In drstemplates.h we have:

```
    /** [5.40: Grid point data - JPEG2000 
     * encoding](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp5-40.shtml) */
    { 40, 7, 0, {4,-2,-2,1,1,1,1} },
    
    /** [5.41: Grid point data - PNG 
     * encoding](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp5-41.shtml) */
    { 41, 5, 0, {4,-2,-2,1,1} },
    
    /** 5.40000: Grid point data - JPEG2000 encoding */
    { 40000, 7, 0, {4,-2,-2,1,1,1,1} },
    
    /** 5.40010: Grid point data - PNG encoding */
    { 40010, 5, 0, {4,-2,-2,1,1} }

```

5.40 and 5.41 are what the WMO docs call JPEG and PNG. They make no mention of 5.40000 and 5.40010. (See https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table5-0.shtml).

So what's going on with 5.40000 and 5.40010? Where did these come from and what are they for? Are they duplicates that can be removed?

@BoiVuong-NOAA or @DusanJovic-NOAA do you know the answer?

**Comment by BoiVuong-NOAA** [comment]
No, I do not know the answer.  The 5.40000 and 5.40010 were in the code in 2007.

**Comment by DusanJovic-NOAA** [comment]
I believe these those are local data representation template number. Probably used at NCEP before WMO standardized them.  Please check with NCO, maybe there are still some programs using them.

**Comment by edwardhartnett** [comment]
OK, I have added this to the doxygen documention in dretemplates.h.
