### ISSUE TITLE
Are we using Jasper correctly?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2c#171]
Looking in enc_jpeg2000.c I see this:

```
    /* Encode image. */
    if ((ier = jpc_encode(&image, jpcstream, opts)))
    {
        printf(" jpc_encode return = %d \n",ier);
        return -3;
    }

```

But jpc_encode() does not seem to be part of Jasper's documentation. Instead, it seems to want us to use jas_image_encode(). (See https://jasper-software.github.io/jasper-manual/releases/version-2.0.33/html/group__image.html#gafc4b2dc6f82b48d9c8e1284005dd45bf).

So what is the deal here? Are we using some secret internal Jasper API?

@DusanJovic-NOAA did you add this code? Can you shed any light on this question?

**Comment by DusanJovic-NOAA** [comment]
No, I did not add that code. But this function is not internal API, we would not be able to use it if it was. It is public function defined here:
https://github.com/jasper-software/jasper/blob/5175dcd845c385ac16c55a8de5c25e3d49bd075e/src/libjasper/include/jasper/jas_image.h#L805
Are there any issues with jpeg2000 encoding?

**Comment by edwardhartnett** [comment]
No issues, just trying to get it tested.

Thanks for the clarification...
