### ISSUE TITLE
Awkward use of pointer arithmetic in code

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2c#183]
C pointer arithmetic is to be used when walking pointers through memory. It is not intended to be used instead of array notiation. All through the code we have this. Here's an example from g2_unpack2.c:

```
    for (j = 0; j < *lencsec2; j++)
        *(*csec2 + j) = cgrib[ipos + j];

```
This should be:

```
    for (j = 0; j < *lencsec2; j++)
        (*csec2)[j] = cgrib[ipos + j];

```

**Comment by BrianCurtis-NOAA** [comment]
Very awkward.

**Comment by edwardhartnett** [comment]
Another awkward thing is the use of 0 when NULL is intended.

Yes, in C, NULL == 0, so you can write:

```
int *a;
a = 0;
```

But it is not as clear as the normal C convention:

`a = NULL;
`
Now it is crystal clear that a is a pointer, not an int.

**Comment by edwardhartnett** [comment]
I believe most of these have been fixed.
