### ISSUE TITLE
We have ifndef USE_PNG, but it is always defined, even if PNG is off

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2c#214]
In enc_png.c we have this code:

#ifndef USE_PNG
void dummy(void) {}
#else   /* USE_PNG */

But USE_PNG is always defined, even if -DUSE_PNG=OFF with cmake.

**Comment by DusanJovic-NOAA** [comment]
USE_PNG is not defined if project is configured with `cmake -DUSE_PNG=OFF`. Unless something is changed in recent commits. What exactly do you want to achieve with all this recent PNG related issues?

**Comment by edwardhartnett** [comment]
User error on my part. I'm getting a handle on it...

I want to achieve the same kind of quality I have in the netCDF libraries. There will be questions about PNG, about JPEG, about other compression methods, about documentation, about building, and about testing. Every single part of this library is subject to review and improvement. 

When I have a full, 100% understanding of every single line of code - that's when I stop asking questions. ;-)
