### ISSUE TITLE
Do not add hardcoded paths to CMakeLists.txt

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [NOAA-EMC/NCEPLIBS-g2c#219]
https://github.com/NOAA-EMC/NCEPLIBS-g2c/blob/4eb7015aedd22e40c9cad102c24010d890db7ee8/CMakeLists.txt#L37

**Comment by edwardhartnett** [comment]
Agree. But I need this to work on MacOS. If  you can find a better way, I am all for it. ;-)
