### ISSUE TITLE
Do we really need to build two copies for each GitHub action test?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2c#229]
In all our workflows we have:
on: [push, pull_request]

This causes each PR to be built twice. I'm not sure why we did this origianly. It could be that it's just example code that I cut-and-pasted when we were first starting to set up these actions. ;-)

On the macOS workflow I have changed this to:
on: [pull_request]

This seems to do just fine. We should do this with all our workflows.

@kgerheiser @DusanJovic-NOAA @aerorahul any comments?

**Comment by kgerheiser** [comment]
Different semantics. With PR only, the Action will only be run when a PR is opened, but on Push it will be run each time you push to a branch.

**Comment by edwardhartnett** [comment]
Yes you're right. Bummer.
