### ISSUE TITLE
Templates header files (drstemplates.h, gridtemplates.h and pdstemplates.h) can be combined into corresponding C files

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [NOAA-EMC/NCEPLIBS-g2c#230]
These three header files (`drstemplates.h`, `gridtemplates.h` and  `pdstemplates.h`) are used only in corresponding .c files:
```
$ grep templates.h *
drstemplates.c:#include "drstemplates.h"
gridtemplates.c:#include "gridtemplates.h"
pdstemplates.c:#include "pdstemplates.h"
```
The structs and template arrays declared and defined in these .h file is only used in corresponding .c files. So I suggest we move the code form .h to .c files and remove .h files. Template arrays can also be declared as static.

**Comment by edwardhartnett** [comment]
Well that seems like a good idea.

Here's a question: is this template info part of the public API? That is, will users of the library ever ask about the template? Or do we assume the user code has full knowledge of what's in the templates, without any help from the g2c library?

**Comment by DusanJovic-NOAA** [comment]
No. It is not public, and it should not be. Publicly accessible functions do not depend on this structure and the content of these arrays. The template values are accessed only via get***template functions. If we move them to .c files and make them static we'll enforce that, ie. make them private.
The user code knows nothing about these templates.The values in these templates are used to decode/encode grib messages which is internal to the library.

**Comment by DusanJovic-NOAA** [comment]
Even the `gtemplate`  struct, currently defined in `grib2.h` is not part of the public API, and can be (and I think should) be moved to `grib2_int.h`
