### ISSUE TITLE
pdstemplate 35 says it needs extension, but no code handles it in extpdstemplate() so no extension is allocated

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2c#240]
pdstemplate 35 says it needs extension, but no code handles it in extpdstemplate() so no extension is allocated.

From pdstemplates.c:

```
/**             VALIDATION --- PDT 4.35
                PDT 4.35  (10/07/2015)
                4.35: Individual ensemble reforecast, control and perturbed,
                at a horizontal level or in a  horizontal layer
                in a continuous or non-continuous time interval. */
    {35,6,1, {1,1,1,1,1,1} }
```

Yet in the function extpdstemplate() there is no handler for number == 35.

There is a test for this in tst_pdstemplates.c.

@BoiVuong-NOAA do you know what is the deal with pdstemplate 35?

**Comment by BoiVuong-NOAA** [comment]
No, I do not.  This was validation of template 4.35 during WMO group developed this template.  We do not have any data to test with it.

**Comment by edwardhartnett** [comment]
I will bump this to the next release...

**Comment by BoiVuong-NOAA** [comment]
Do you have the time for the next release ?

**Comment by edwardhartnett** [comment]
Do you know of some reason why a release is needed?

**Comment by BoiVuong-NOAA** [comment]
Users in UPP are waiting for this release to work on their development. I have given them the code for testing since in 9/2021.

**Comment by edwardhartnett** [comment]
Who is involved in this code in UPP?

Why are they waiting on the next release? I am not aware that it contains any new feature or bugfix that would be important to them...

**Comment by BoiVuong-NOAA** [comment]
These are new fields and requested by Tracy Hertneky and Lin L Zhu and Wen Meng.
If you can not release now, then they have to wait for it.  Note: It is not a bugfix.

**Comment by edwardhartnett** [comment]
We can release. Are you going to add the fields to this repo as well?

**Comment by BoiVuong-NOAA** [comment]
Yes, I all add these fields in the test code. Note: These fields are not used in G2C library.

**Comment by edwardhartnett** [comment]
I also note that there is no extension info provided for template 35 in the fortran library either.
