### ISSUE TITLE
get rid of jasper?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2c#247]
Do I remember correctly that we were planning on getting rid of jasper from our builds?

@kgerheiser @DusanJovic-NOAA do you guys know if we are planning to stop using jasper? And what will we be using instead?

**Comment by DusanJovic-NOAA** [comment]
I don't know. I see NCO still installs Jasper as a default jpeg2000 library on production machines.

**Comment by edwardhartnett** [comment]
Jasper is troublesome. The maintainer has a lot of fun, original ideas of how to do things. See #245 for the latest example.

**Comment by DusanJovic-NOAA** [comment]
Is this issue present in the version that we currently use, 2.0.22?

**Comment by edwardhartnett** [comment]
No, it appears in the jasper3.x series.

**Comment by edwardhartnett** [comment]
OK, I have a fix so I guess there's no urgency about removing jasper from the build.
