### ISSUE TITLE
Compatibility with ncl?

### ISSUE THREAD

**Issue by asesidaa** [NOAA-EMC/NCEPLIBS-g2c#252]
Hi,
I am trying to build [ncl](https://www.ncl.ucar.edu/) with grib2 support. However, ncl is replying on an old patched version of [g2clib](http://www.ncl.ucar.edu/Download/files/g2clib-1.6.0-patch.tar.gz), which builds `libgrib2c.a` instead of `libg2c.a`. And even if I changed the project name in CMakeLists.txt to `grib2c`and build `ncl`, I can only get
```
fatal:GdsCEGrid: Invalid grid detected
fatal:NclGRIB2: Couldn't handle dimension information returned by grid decoding
```
so I assume some breaking changes have been introduced (or I have made some mistakes in compiling)
It is possible to make newer version of g2c compatibe with ncl?

Thank you!

**Comment by edwardhartnett** [comment]
I'm afraid you will have to be more specific. I am not terribly familiar with NCL (NCAR Command Language?)

I can't address what the patch to refer to might have done, but we have not made any backward incompatible changes in g2c, so it should continue to work wherever it used to work.

**Comment by asesidaa** [comment]
I have tested and it seems that v1.6.2 works, while v1.6.4 doesn't, so maybe some changes in between have caused this incompatibility?

**Comment by kgerheiser** [comment]
Looking at the release notes and history there don't appear to be many code changes. Wonder if it's related to https://github.com/NOAA-EMC/NCEPLIBS-g2c/pull/121/files

And now some types are mismatched?

**Comment by asesidaa** [comment]
```ncl
begin
  if (fileexists(filename)) then
    print("Exists!")
  end if

  if ( .not.isfilepresent(filename ) ) then
    print( " ... source grid file not found : "+ filename )
    exit
  end if
end
```

This is the test script I used, invoked using `ncl 'filename="file.grb2"' test.ncl` 
When succeed, ncl should just print `Exists!` and exit, however, when using v1.6.4, `ncl` will error out parsing grib2 files (since `isfilepresent` will actually parse the file and only report true if the file is in correct format)

**Comment by asesidaa** [comment]
> Looking at the release notes and history there don't appear to be many code changes. Wonder if it's related to https://github.com/NOAA-EMC/NCEPLIBS-g2c/pull/121/files
> 
> And now some types are mismatched?

This seems to be the problem, after change types back to
```C
typedef int g2int; 
typedef unsigned int g2intu;
``` 
`ncl` can now parse grib files without issue.
@edwardhartnett maybe this can be documented?
Also with regard to library name, is it possible to produce `libg2c.a` and `libgrib2c.a` at the same time for maximum compatibility?

**Comment by kgerheiser** [comment]
I don't think we will provide an alternate library name within the build. It's kind of hacky just for this particular purpose, and NCL is in maintenance mode.

If you want to build NCL using Spack and g2c I would recommend applying a patch to NCL using Spack so it works with this version of g2c. A quick look at the NCL source shows that changing the library name is a simple text replacement of `-lgrib2c` with `-lg2c` which is easily accomplished with Spack patch or Makefile filter in the edit phase.

```
install/make-external/Build-NCL.sh
149:cp -v libgrib2c.a ${ncl_dev_lib}
351:#g/lgrib2c/d
353:##define GRIB2lib   -lgrib2c -ljasper -lpng -lz
```

And for the source kind issue. My bet is that it's some NCL source using a 32-bit integer. And that could also be fixed with a source code patch.

**Comment by kgerheiser** [comment]
Poked around NCL a little, and it's this file (https://github.com/NCAR/ncl/blob/develop/ni/src/ncl/NclGRIB2.h) that hard codes the types as `int` instead of using `g2int`, which is the proper usage. You could try changing those to `g2int` and see what happens.
