### ISSUE TITLE
Doxygen documentation needs to be updated on branch gh-pages

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2c#26]
After #25 is complete, the documentation needs to be rebuilt, and then copied to the gh-pages branch.

@BoiVuong-NOAA this is a good time to handle this, since you are code manager for this repo.

What you do is first build the docs:

```
git clone git@github.com:NOAA-EMC/NCEPLIBS-g2c.git 
cd NCEPLIBS-g2c
mkdir build
cd build
cmake -DENABLE_DOCS=ON ..
make
```

Now the docs are in NCEPLIBS-g2c/build/docs/html.

Then, take another clone of the repo, switch to the gh-pages branch, delete contents, and add the HTML output:

```
git clone git@github.com:NOAA-EMC/NCEPLIBS-g2c.git dox_NCEPLIBS-g2c
cd dox_NCEPLIBS-g2c
git checkout gh-pages
git rm -rf *
cp -R NCEPLIBS-g2c/build/docs/html/* .
git add *
git commit -m "updated docs" -a
git push
```

Take care that you are on the gh-pages branch before doing `git rm -rf *`!

After you do this, in a few minutes, github will update the documentation at  https://noaa-emc.github.io/NCEPLIBS-g2c/. It does take a few minutes to update.

Ask for help if you need it. This will have to be done every release, on every repo. ;-)

**Comment by BoiVuong-NOAA** [comment]
Hi Ed, 
I will work on Doxygen for g2c in next week.  I am working on bufr lib for gsf downstream and util_shared for gsf v15.3.3.

**Comment by edwardhartnett** [comment]
It's not acceptable for the documentation to be broken.

I have done the update.
