### ISSUE TITLE
Are we using the wrong value for GRIB Master Tables Version Number when we create files?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2c#288]
In section 1 of GRIB2 messages we have (from our GRIB documentation):

> GRIB master tables version number (currently 2) (See Table 1.0) (See note 1)

Table 1.0 is here:
https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table1-0.shtml

Since we are keeping our code tables up to date with WMO changes, I would assume we should be using:

`25 | Version Implemented on 06 May 2020
`

But when I look at the test file we are using: gdaswave.t00z.wcoast.0p16.f000.grib2 I see that it uses:

		GRIB master tables version number: Version implemented on 4 November 2003

which is code 2.

Why are we still using code 2 when we have clearly updated our tables since 2003? Shouldn't we be using 25 now?

Or am I misunderstanding the purpose of this field?

@Hang-Lei-NOAA @BoiVuong-NOAA @DusanJovic-NOAA do you know what is going on with our use of our GRIB master table version number?

**Comment by DusanJovic-NOAA** [comment]
I do not think WMO requires the use of latest available master table to be used at a time of message creation. I believe it's perfectly legal to use previous versions as long as the encoded table version number corresponds to the templates used to encode the message. i.e message must be valid. Now, why these wave files use 'old' master table version I do not know, but that should not be an issue. Maybe the program used to encode these files hard-coded version 2.

**Comment by BoiVuong-NOAA** [comment]
Hi Ed,

All NCEP GRIB2 products are using GRIB master tables version number 2 as 
default.  Because of AWIPS products, We have tried to change the GRIB2 
master table to current version and It failed. Except WAFS products are 
using GRIB master tables version number 6.

Thanks,

Boi

**Comment by DusanJovic-NOAA** [comment]
BTW, current master table version is 29.1 not 25.
https://github.com/wmo-im/GRIB2/releases

**Comment by BoiVuong-NOAA** [comment]
Dusan,

You are correct. All users (HPC, CPC, AWC, FAA, all AWIPS forecast 
offices, ... ) have used to encode our NCEP products at GRIB master 
tables version number 2.

**Comment by edwardhartnett** [comment]
@DusanJovic-NOAA do the contents of the templates change from version to version?

In other words are there templates in version 2 which are different in version 29.1? And are we expect to use the version 2 templates only in our files, since we say version 2?

@BoiVuong-NOAA can you elaborate about the AWIPS issue? So we provide GRIB2 files to AWIPS users? And if we change our code for master version number, then AWIPS cannot read our file?

**Comment by BoiVuong-NOAA** [comment]
Hi Ed and Dusan,

No, The templates will not change from version to version. When WMO 
release new version, it may add some new templates, new parameters or 
fix bug in templates (if user found bugs).  At NCEP, We will use master 
table version 2 as a super set to cover all grib master tables version.

AWIPS has been developed with hard code for GRIB2 as master grib version 
2.  It is hard for them to change all codes in all forecast offices. 
yes, You are correct. The AWIPS cannot read our file if it has master 
table version 3, 4, ... ect.   We can do it in the future when AWIPS is 
going to update their machine.

I think AWIPS has carried over from GRIB1 which it master version 1.

Thanks,

Boi

**Comment by DusanJovic-NOAA** [comment]
If I understand your question correctly, you are asking whether template(n) is strict subset of template(n+1). I do not know, I hope it is, it better be, otherwise we must maintain code for all versions.

**Comment by edwardhartnett** [comment]
OK, thanks for the answers @BoiVuong-NOAA !

I will close this issue.
