### ISSUE TITLE
Cause CMake to update version in header file src/grib2.h

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2c#29]
I see this in src/grib2.h:

`#define G2_VERSION "g2clib-1.6.0"
`￼

So presumably this also has to be updated in the 1.6.2 release. (@Hang-Lei-NOAA )

Also this should not be in the header file. Instead, we should have a grib2.h.in file, and CMake should fill in the version using variable substitution.

**Comment by Hang-Lei-NOAA** [comment]
yes you are right

**Comment by Hang-Lei-NOAA** [comment]
The old rule is that the code manager should tag and release.
I suggest that let the code manager remove Tag 1.6.2, which I created for
hpc-stack installation and create a new tag/release.

Also the tag name convention needs to be discussed.  There were many
changes in naming the Tag in the past several years.
The latest rule was only v2.2.3 for a tag in a repo.    We used to have
like nemsio_v2.2.3.  This needs to be determined and announced.

**Comment by edwardhartnett** [comment]
Do not undo this now, we are almost complete with the full release.

In future, please follow the procedure, but it will take us some time to get used to it.

We can discuss the tag name in the thread under NCEPLIBS. I don't mind what it is, but it should be the same across NCEPLIBS. It it has not been, then we will make it so moving forward.

**Comment by edwardhartnett** [comment]
Also this issue does not relate to the 1.6.2 release. That can be fixed manually. THis issue is to automate this for future releases, so we won't have to manually update src/grib2.h each time we do a release.

**Comment by Hang-Lei-NOAA** [comment]
I agree with you to have the grib2.h.in file.
It is very good with clear rules announced to define each step and role of
code manager and developers.

**Comment by edwardhartnett** [comment]
OK, turns out that this macro, G2_VERSION, is not used anywhere in the code. So can it be removed? Or is it used by other codes?

**Comment by Hang-Lei-NOAA** [comment]
I believe it is okay to be removed. I did not see where to use it.

**Comment by DusanJovic-NOAA** [comment]
Please do not remove `G2_VERSION`. It's used by applications to identify the library version. In fact I think it should be changed to only contain the version number, without 'g2clib-' prefix. Similar to how other libraries provide version number in their header files:
zlib: `#define ZLIB_VERSION "1.2.11"`
jasper: `#define	JAS_VERSION "2.0.25"`
libpng: `#define PNG_LIBPNG_VER_STRING "1.6.37"`
netcdf: `#define NC_VERSION       "4.5.0"`

**Comment by edwardhartnett** [comment]
@DusanJovic-NOAA I came to the same conclusion - it should not be removed.

I will change it as you suggest.
