### ISSUE TITLE
Support for MET and METplus

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2c#35]
@BoiVuong-NOAA you mentioned this in your email, but I don't know the details. I know about MET and METplus (see https://github.com/NOAA-EMC/hpc-stack/issues/101).

What has to be done to the g2c library to support MET and METplus?

**Comment by BoiVuong-NOAA** [comment]
Met v1.9.0 requires gc2 v1.6.2 to install in NWPROD

**Comment by edwardhartnett** [comment]
OK, g2c-1.6.2 is about to be released as part of hpc-stack-1.1.0, and installed on our HPC systems. So it looks like we already have support for MET and METplus, which is good.

**Comment by BoiVuong-NOAA** [comment]
Hi Ed,
Do I need to submit "code deliver form" for G2C v1.6.2 to NCO ?  Mallory is waiting the G2C library to compile with MET Plus.
Thanks,
Boi

**Comment by edwardhartnett** [comment]
I don't know what a code deliver form is.

hpc-stack-1.1.0 has been installed on all the tier 1 machines, which includes g2c-1.6.2.

Does that answer your question?

**Comment by BoiVuong-NOAA** [comment]
Hi Ed,
The "code deliver form" is a form to submit to NCO for code changes in operational (such as library, GFS models, NAM, etc.)  Then, NCO will checkout the code from GitHub repo and install it to nwtest for testing.  If the test is OK, NCO will schedule the date for implementation in operational (NWPROD).  All users (in NCEP or outside users) will be notified by the NCO RFC.
The "code deliver form" is at this link:
https://docs.google.com/a/noaa.gov/forms/d/1vPwPn2RPQ-fue_th_ZYr5a_IcYUbjmEu0t8R49b-QSY/viewform?edit_requested=true

If the hpc-stack-1.1.0 has been installed on all the tier 1 machines, then I do not need to work it.   What is tier 1machine ? It is included DELL and CRAY (WCOSS machine).

Do you have any access on WCOSS machine ?

Thanks,
Boi

**Comment by kgerheiser** [comment]
It's for WCOSS Cray, right? @Hang-Lei-NOAA  just installed the updated NCEPLIBS at:

`module use /usrx/local/nceplibs/NCEPLIBS/cmake/install/NCEPLIBS-v1.3.0/modules`

`module load g2c/1.6.2`

It will be ready in a moment. There's a small problem with the modules that's being fixed.

**Comment by BoiVuong-NOAA** [comment]
Kyle, I do not see it on DELL.
Met Plus needs it on both DELL and CRAY.   Will Hang install it on DELL (Venus and Mars) ?
Will it install in NWPROD  soon ?

**Comment by kgerheiser** [comment]
On Dell, it's installed as part of hpc-stack. Is that sufficient?

```
module use /usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/modulefiles/stack
module load hpc/1.1.0
module load hpc-ips/18.0.1.163
module load g2c/1.6.2
```


I don't know about `nwprod`

**Comment by BoiVuong-NOAA** [comment]
Met version 1.0.9 requires to install in NWPROD. Therefore, The hpc-stack needs to install in NWPROD.  NCO will not accept any libraries in DEV to be used in operational.   Do you know when the hpc-stack will be installed in NWPROD ?

**Comment by kgerheiser** [comment]
hpc-stack won't be installed in NWPROD.

Is installing it in nwprod something we need to ask NCO to do?

**Comment by BoiVuong-NOAA** [comment]
Then, We need to submit "code deliver form" to NCO to install it in nwprod ?  Can you submit the request to NCO ? Is hpc-stack ready for operational on WCOSS ?

**Comment by kgerheiser** [comment]
hpc-stack won't be used operationally. It is for developers.

**Comment by Hang-Lei-NOAA** [comment]
NCO do not have a plan to install our existing hpc-stack on nwprod.
Previously, the hpc-stack-nco with the NCO_V on is for NCO requirements.
They need to use their third party libs.

**Comment by BoiVuong-NOAA** [comment]
I see. I will submit the g2c library v1.6.2 to NCO to install in nwprod.

**Comment by edwardhartnett** [comment]
I believe this issue can be closed. Please let me know if I'm wrong...

**Comment by BoiVuong-NOAA** [comment]
Yes, The MET has been using the g2c v1.6.3 on WCOSS and worked fine,
