### ISSUE TITLE
Cleanup CMake shared vs static libraries

### ISSUE THREAD

**Issue by EricEngle-NOAA** [NOAA-EMC/NCEPLIBS-g2c#408]
On the heels of lessons learned from enabling static vs. shared libs in NCEPLIBS-ip and NCEPLIBS-sp, we sould implement the same CMake configuration here too.

**_NOTE:_** g2c as of 1.7.0 can build shared libs, but cannot create simultaneously with static libs.

**Comment by edwardhartnett** [comment]
Should this issue be closed?

**Comment by EricEngle-NOAA** [comment]
Yes.
