### ISSUE TITLE
XML files generated from build should be installed to share/

### ISSUE THREAD

**Issue by EricEngle-NOAA** [NOAA-EMC/NCEPLIBS-g2c#409]
XML files generated in the build process are being installed to `CMAKE_INSTALL_PREFIX/lib`.  Since these are static/data files, should we install them to `CMAKE_INSTALL_PREFIX/share` instead?

**Comment by edwardhartnett** [comment]
Sure, biut I am also going to remove that from the build...

**Comment by EricEngle-NOAA** [comment]
Ah OK.  No need to worry about it then.
