### ISSUE TITLE
Node.js warnings in CI for cache@v2 and checkout@v2

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2c#417]
For some time we have been getting warnings like this in our CI system:

`Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/cache@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.`

Well I finally figured out that it wants us to update from using "cache@v2" to using "cache@v3". For example, in the developer.yml file for g2c we have:

```
    - name: cache-jasper
      id: cache-jasper
      uses: actions/cache@v2

```
We need to change this to:

```
    - name: cache-jasper
      id: cache-jasper
      uses: actions/cache@v3

```

We need to do this for cache@v2, checkout@v2, and upload-artifact@v2.

@AlexanderRichert-NOAA @Hang-Lei-NOAA @GeorgeGayno-NOAA @jbathegit take note...

**Comment by jbathegit** [comment]
Noted - thanks!  I just submitted a corresponding PR for NCEPLIBS-bufr.
