### ISSUE TITLE
DRS Template 5.42 which references CCSDS/AEC Compression

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2c#424]
Add support for DRS Template 5.42 which references CCSDS/AEC Compression

**Comment by EricEngle-NOAA** [comment]
Any movement on this?  I could take a shot at implementing this.

**Comment by edwardhartnett** [comment]
Sorry I'm still pretty far from implementing this.

I've been working on the Fortran library and utilities, which have had a long backlog of important bugs to fix. Once those are caught up I will return to the C library.

If you want to implement this, that would be fantastic. You will not neglect unit testing, I'm sure...

**Comment by edwardhartnett** [comment]
I believe this is now complete.

**Comment by JKrobNESDIS** [comment]
Glad to see progress on this issue - will the Fortran library be updated as well, by chance (as per the original request)?

**Comment by edwardhartnett** [comment]
The next g2 release will depend on g2c and will include fortran wrappers around the AEC compression. In other words, yes, the next g2 release will support this compression, but it will not re-implement this code, it will simply start to use the C library.

There are other cases where there are duplicate code and functionality between the two libraries. I will start to clean that away, with all the core functionality in the g2c library, exposed by wrappers in g2 library.
