### ISSUE TITLE
make test failure

### ISSUE THREAD

**Issue by LLLavinia** [NOAA-EMC/NCEPLIBS-g2c#426]
<img width="553" alt="捕获1" src="https://github.com/NOAA-EMC/NCEPLIBS-g2c/assets/32565388/2a9c7599-4e9d-4757-9fc3-2471c298b01c">

<img width="399" alt="捕获2" src="https://github.com/NOAA-EMC/NCEPLIBS-g2c/assets/32565388/38df9aa0-7fab-4928-8a87-24502c66cd15">

<img width="363" alt="捕获3" src="https://github.com/NOAA-EMC/NCEPLIBS-g2c/assets/32565388/7e995bd4-178e-4c10-88fe-c9fc58190533">

<img width="372" alt="捕获4" src="https://github.com/NOAA-EMC/NCEPLIBS-g2c/assets/32565388/fc6e0f30-d3c6-48c5-8805-a232de674873">

**Comment by LLLavinia** [comment]
on MacOS Monterey 12.6.3

**Comment by edwardhartnett** [comment]
Can you send me the full output from the cmake step?

Also, we're pretty busy here at the EMC. If you want some help, please take the time and effort to put together a proper issue, with some actual information. Surely you can see that with the information you have provided, it's not going to be possible for us to give you any reasonable answer.

**Comment by LLLavinia** [comment]
> Can you send me the full output from the cmake step?
> 
> Also, we're pretty busy here at the EMC. If you want some help, please take the time and effort to put together a proper issue, with some actual information. Surely you can see that with the information you have provided, it's not going to be possible for us to give you any reasonable answer.

Thank you for your reply!
I have uploaded screenshots of all the steps. Sorry for being too brief before, but I just followed the steps on README.md to install. Is there any other information I can provide?
Are those errors related to OS? It is MacOS Monterey 12.6.3. Thank you again for your help!

**Comment by edwardhartnett** [comment]
Try setting the LD_LIBRARY_PATH to the directory where jasper is installed and try again...

**Comment by edwardhartnett** [comment]
Is this still a problem?

I've just done a new release, can you try it?
