### ISSUE TITLE
Release 1.8.0

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [NOAA-EMC/NCEPLIBS-g2c#435]
@edwardhartnett @Hang-Lei-NOAA as far as the release notes etc., is v1.8.0 ready to release? If so I can fire it off so that grib-util can run the copygb2 tests based on a release.

**Comment by edwardhartnett** [comment]
I turned off the g2c testing in grib_utils (temporarily) and did a grib_utils release. Now I'm working on a g2c release...

**Comment by edwardhartnett** [comment]
OK, planning to release after #456 is merged...
