### ISSUE TITLE
Check for jasper version

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2c#46]
Check for jasper version

**Comment by edwardhartnett** [comment]
What version should we be requiring? @kgerheiser do you know?

**Comment by kgerheiser** [comment]
There might be some version of Jasper that doesn't work, but I'm not sure. Besides that issue with Intel compilers I've built things with Jasper 1.900.1 (really old) and recent 2.x.x releases as well.

**Comment by edwardhartnett** [comment]
What is the version that resolved the intel compiler issue? 25? We can use that one...

**Comment by kgerheiser** [comment]
Yes, 2.0.25
