### ISSUE TITLE
Change C++ comments to C comments...

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2c#47]
Let's decide what language we are using, and stick to it.

As it says in the README:

> This C source code conatins many uses of the C++ comment style "//". Please make sure you include the appropriate compiler option in the CFLAGS variable in the makefile to allow the use of "//" comment indicators.

Well that is just silly. C has comments, no need to try and make it into C++.

**Comment by DusanJovic-NOAA** [comment]
The "`//`" are not C++ style comments. They are valid C comments.

**Comment by DusanJovic-NOAA** [comment]
https://github.com/NOAA-EMC/NCEPLIBS-g2c/issues/31

**Comment by edwardhartnett** [comment]
They are valid C comments in C99, but plenty of people don't use c99 version compilers. This comes up frequently with netcdf-c and PIO support issues. It's easier to use traditional C comments than deal with support issues.

Is there some problem with traditional C comments?

**Comment by edwardhartnett** [comment]
This is partially complete, will be finished in the next release.

**Comment by edwardhartnett** [comment]
Instead we will try to turn on c99 in compiles... (see #129).
