### ISSUE TITLE
Should the include file name match the lib name?

### ISSUE THREAD

**Issue by EricEngle-NOAA** [NOAA-EMC/NCEPLIBS-g2c#482]
Should the include file for g2c be `g2c.h` instead of `grib2.h` to match library file naming?

**Comment by edwardhartnett** [comment]
Yes, but what about backward compatibility?

**Comment by EricEngle-NOAA** [comment]
Is a valid approach to provide a symlink until some version?  Maybe v2.0.

This is more or less stirring up conversation.  If you think it is not a big deal, feel free to close.

**Comment by edwardhartnett** [comment]
We will just live with what we've got for now...
