### ISSUE TITLE
Enforce proper code formatting

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [NOAA-EMC/NCEPLIBS-g2c#509]
This section of code does not look properly indented, which makes it hard to read and reason about it:

![image](https://github.com/user-attachments/assets/e1baf765-97b5-4f9d-abb9-6a665c80dc7a)

This is because in my editor tabs are displayed as 4 spaces. We should not use tabs in the source code.

To fix:
1) Replace all tabs with spaces in all source files.
2) Delete trailing spaces.
3) Use clang-format to uniformly and consistently reformat all source code.
4) Enforce proper formatting in CI

**Comment by edwardhartnett** [comment]
Agree.

We are using 4-spaces, no tabs. If you see anything else, feel free to correct.

I have never used clang-format. I would welcome a CI that demonstrates this in the CI.

**Comment by DusanJovic-NOAA** [comment]
I added `.clang-fomat` in this commit https://github.com/NOAA-EMC/NCEPLIBS-g2c/commit/f32fb5d8a08ade69828d9e41147bdc14395ae3dd

And with those settings I ran it in the src directory on all source files, see this [commit](https://github.com/NOAA-EMC/NCEPLIBS-g2c/commit/601de0be89beded3abd730bf7c99df21a65b3071?w=1)  (ignoring whitespace changes)

Is this acceptable format/style?

I ran it locally on my laptop, I do not know how to integrate it in CI.

**Comment by edwardhartnett** [comment]
Yes, that looks great. Let's get your commits merged and I will put clang-format in the CI.

Thanks for this, it's really helpful. I'll suggest it for the netcdf-c repo.
