### ISSUE TITLE
Update authors in README

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2c#55]
The readme says:
```
Authors
Boi Vuong, Hang Lei
```
Yet when I look in the code, most of it seems to be written by "Gilbert".

Who is Gilbert and why are we not crediting him or her with authorship?

**Comment by edwardhartnett** [comment]
@BoiVuong-NOAA and @Hang-Lei-NOAA do you know the answer to this question?

**Comment by BoiVuong-NOAA** [comment]
I do not know how to answer your ? Yes, Gilbert was developer for G2 and G2C.    When We moved all codes to github and Mark assigned code manager to me and Hang

**Comment by edwardhartnett** [comment]
OK, the author is different from the code manager. Do you know Gilbert's first name?

**Comment by BoiVuong-NOAA** [comment]
His first name is Stephen.
