### ISSUE TITLE
use of strsep() fails to find function definition in strings.h on Windows with clang

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2c#555]
I get this warning:

D:/a/NCEPLIBS-g2c/NCEPLIBS-g2c/g2c/src/g2ccsv.c:222:23: error: implicit declaration of function 'strsep'; did you mean 'strset'? [-Wimplicit-function-declaration]
  222 |                 tmp = strsep(&buf, "\"");
      |                       ^~~~~~
      |                       strset
D:/a/NCEPLIBS-g2c/NCEPLIBS-g2c/g2c/src/g2ccsv.c:222:21: error: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  222 |                 tmp = strsep(&buf, "\"");
      |                     ^
D:/a/NCEPLIBS-g2c/NCEPLIBS-g2c/g2c/src/g2ccsv.c:223:21: error: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  223 |                 tmp = strsep(&buf, "\"");
      |                     ^
D:/a/NCEPLIBS-g2c/NCEPLIBS-g2c/g2c/src/g2ccsv.c:225:21: error: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  225 |                 tmp = strsep(&buf, ",");
      |                     ^
D:/a/NCEPLIBS-g2c/NCEPLIBS-g2c/g2c/src/g2ccsv.c:229:21: error: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  229 |                 tmp = strsep(&buf, ",");
      |                     ^

Looks like we should use strtok() instead. See https://stackoverflow.com/questions/58244300/getting-the-error-undefined-reference-to-strsep-with-clang-and-mingw.

@AlysonStahl-NOAA can you convert this code to strtok()? Hopefully sometime this week?

**Comment by AlysonStahl-NOAA** [comment]
Unfortunately strtok won't work for this case because there are some fields which contain commas and there are multiple empty columns which aren't consistent within the rows. In general, strtok doesn't seem to handle edge cases very well.

There doesn't seem to be a clean way to work around this that I can find other than to just create a new function that implements strsep().
