### ISSUE TITLE
Do a proper release

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2c#6]
I note there are no actual releases on github. There should be. ;-)

For releases see https://github.com/NOAA-EMC/NCEPLIBS/issues/131

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA and @BoiVuong-NOAA we need a proper release with:
* tagged repo
* release notes on GitHub
* tarball distribution uploaded to github.

I'll start with the release notes...

**Comment by Hang-Lei-NOAA** [comment]
Hi, Ed and Boi

I added a brief release note for the changes.
Could you please modify if more detailed information is needed?

Thanks,
Hang
