### ISSUE TITLE
Remove unneeded and cryptic "ORG: W/NP11" as part of author tags

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2c#73]
We have author tags like this:

`@author Gilbert ORG: W/NP11`

What does ORG: W/NP11 mean? Does that convey anything long-time NOAAites? It means nothing to me...

**Comment by Hang-Lei-NOAA** [comment]
I am not sure what is W/NP11. From ORG, it looks like the organization.

**Comment by edwardhartnett** [comment]
OK, since we have no idea what it means, let's remove it everywhere.

**Comment by Hang-Lei-NOAA** [comment]
Okay, I will open a ticket to remove these already in g2, after the
existing pull request
